name: LanguagePlugin
version: @version@
main: com.github.highright1234.language_plugin.LanguagePlugin
api-version: 1.16
commands:
  test:
    usage: 테스트임
    description: 테스ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ트

depend: [LocaleLib]
